import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import { BusinessWorldError, readWorkspace, mutateWorkspace, workspaceOwner } from '../lib/business-world/workspace-service';
import { getBusinessWorldSnapshot, runScenarioExperiment, businessWorldWriteSchema } from '../lib/business-world/real-service';
import saveTool from '../agent/tools/business_world_save_record';
import { toolOwner } from '../lib/business-world/tool-auth';

// This is an actual isolated on-disk database, not a canned database response.
process.env.BUSINESS_WORLD_SQLITE_PATH=join(mkdtempSync(join(tmpdir(),'business-world-verify-')),'workspace.sqlite');
delete process.env.DATABASE_URL;delete process.env.VERCEL;
const owner=workspaceOwner('integration-operator'),other=workspaceOwner('other-operator');
const metrics={gmv:10000,conversion:3,engagement:400,roi:2,repeat:20,live:200,revenue:9000};
const save={kind:'save-snapshot',name:'审计人工录入',notes:'隔离验证数据；不是平台观测',metrics};
const rejects=(fn:()=>unknown,code:string)=>assert.rejects(fn as ()=>Promise<unknown>,(e:unknown)=>e instanceof BusinessWorldError&&e.code===code);

test('shared workspace persistence and authority contract',async t=>{
 await t.test('empty database returns empty state without remote/demo fallback',async()=>{const w=await readWorkspace(owner);assert.equal(w.revision,0);assert.equal(w.state.snapshot,null);});
 await t.test('server stamps a real persisted manual snapshot',async()=>{const w=await mutateWorkspace(owner,{expectedRevision:0,command:save});assert.equal(w.revision,1);assert.deepEqual(w.state.snapshot?.metrics,metrics);assert.equal(w.state.snapshot?.status,'unverified');assert.equal(w.state.snapshot?.sourceType,'manual');assert.match(w.state.snapshot!.id,/^[a-f0-9-]{36}$/);assert.deepEqual((await readWorkspace(owner)).state,w.state);});
 await t.test('different authenticated owners never share records',async()=>{const w=await readWorkspace(other);assert.equal(w.revision,0);assert.equal(w.state.snapshot,null);assert.notEqual(w.workspaceId,owner);});
 await t.test('missing baseline cannot create a scenario',async()=>{await rejects(()=>mutateWorkspace(other,{expectedRevision:0,command:{kind:'run-scenario',lever:'ad_efficiency',change:20,prompt:'测试'}}),'baseline-required');assert.equal((await readWorkspace(other)).revision,0);});
 await t.test('manual input cannot forge official provenance or owner',async()=>{await rejects(()=>mutateWorkspace(owner,{expectedRevision:1,command:{...save,sourceType:'official-api'}}),'invalid-input');await rejects(()=>mutateWorkspace(owner,{expectedRevision:1,owner:other,command:save}),'invalid-input');assert.equal(businessWorldWriteSchema.safeParse({sourceType:'official-api'}).success,false);});
 await t.test('numbers are bounded and empty/negative/infinite are rejected',async()=>{for(const value of [-1,Infinity,''])await rejects(()=>mutateWorkspace(owner,{expectedRevision:1,command:{...save,metrics:{...metrics,gmv:value}}}),'invalid-input');assert.equal((await readWorkspace(owner)).revision,1);});
 await t.test('scenario is lever-specific and never changes its baseline',async()=>{const before=await readWorkspace(owner);const result=await runScenarioExperiment({prompt:'广告效率提升',lever:'ad_efficiency',changePercent:20,expectedRevision:1},owner);assert.equal(result.result.modeledMetrics.gmv,10700);assert.equal(result.result.modeledRoi,2.4);assert.equal(result.result.modeledConversionRate,3);assert.deepEqual(result.workspace.state.snapshot,before.state.snapshot);assert.deepEqual(result.workspace.state.scenarios[0].baseline,before.state.snapshot);});
 await t.test('a different lever cannot scale unrelated ROI or conversion',async()=>{const r=await runScenarioExperiment({prompt:'内容互动提升',lever:'content_engagement',changePercent:20,expectedRevision:2},owner);assert.equal(r.result.modeledMetrics.engagement,480);assert.equal(r.result.modeledMetrics.gmv,10500);assert.equal(r.result.modeledRoi,2);assert.equal(r.result.modeledConversionRate,3);});
 await t.test('unsupported dimensions are not invented',async()=>{const s=await getBusinessWorldSnapshot(owner);assert.equal(s.data?.content.engagementRate,null);assert.equal(s.data?.ads.budget,null);assert.equal(s.provenance.sourceMode,'manual-unverified');assert.equal(s.provenance.asOf,null);await rejects(()=>runScenarioExperiment({prompt:'未知时长',lever:'live_watch_time',changePercent:20,expectedRevision:3},owner),'invalid-input');});
 await t.test('reports and notes retain immutable source after later updates',async()=>{let w=await readWorkspace(owner);const scenario=w.state.scenarios[0];w=await mutateWorkspace(owner,{expectedRevision:w.revision,command:{kind:'create-report',title:'固定基准报告',scenarioId:scenario.id}});const original=w.state.reports[0].baseline,reportId=w.state.reports[0].id;w=await mutateWorkspace(owner,{expectedRevision:w.revision,command:{kind:'save-note',reportId,note:'人工意见，不是模型结论'}});w=await mutateWorkspace(owner,{expectedRevision:w.revision,command:{...save,name:'后续记录',metrics:{...metrics,gmv:20000}}});assert.deepEqual(w.state.reports[0].baseline,original);assert.equal(w.state.reports[0].note,'人工意见，不是模型结论');assert.notEqual(w.state.snapshot!.id,original.id);});
 await t.test('stale writers cannot overwrite a newer revision',async()=>{const w=await readWorkspace(owner);await rejects(()=>mutateWorkspace(owner,{expectedRevision:w.revision-1,command:save}),'conflict');assert.deepEqual(await readWorkspace(owner),w);});
 await t.test('two concurrent writers yield exactly one committed update',async()=>{const w=await readWorkspace(owner);const results=await Promise.allSettled([mutateWorkspace(owner,{expectedRevision:w.revision,command:{...save,name:'并发一'}}),mutateWorkspace(owner,{expectedRevision:w.revision,command:{...save,name:'并发二'}})]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.equal(results.filter(x=>x.status==='rejected').length,1);assert.equal((await readWorkspace(owner)).revision,w.revision+1);});
 await t.test('clients cannot replace server scenario or report histories',async()=>{const w=await readWorkspace(owner);await rejects(()=>mutateWorkspace(owner,{expectedRevision:w.revision,state:{reports:[]},command:save}),'invalid-input');await rejects(()=>mutateWorkspace(owner,{expectedRevision:w.revision,command:{kind:'replace-state',state:{}}}),'invalid-input');});
 await t.test('ambiguous storage config and serverless local storage fail closed',async()=>{process.env.DATABASE_URL='postgresql://unused.invalid/never-contacted';try{await rejects(()=>readWorkspace(owner),'unavailable');}finally{delete process.env.DATABASE_URL;}process.env.VERCEL='1';try{await rejects(()=>readWorkspace(owner),'unavailable');}finally{delete process.env.VERCEL;}});
 await t.test('missing storage does not silently return a different database',async()=>{const path=process.env.BUSINESS_WORLD_SQLITE_PATH;delete process.env.BUSINESS_WORLD_SQLITE_PATH;try{await rejects(()=>readWorkspace(owner),'unavailable');}finally{process.env.BUSINESS_WORLD_SQLITE_PATH=path;}});
 await t.test('corrupt persisted state fails safely instead of becoming data',async()=>{const corrupt=workspaceOwner('corrupt');const db=new DatabaseSync(process.env.BUSINESS_WORLD_SQLITE_PATH!);db.prepare('INSERT INTO business_world_workspace VALUES(?,?,?,?)').run(corrupt,1,'{broken',new Date().toISOString());db.close();await rejects(()=>readWorkspace(corrupt),'unavailable');});
 await t.test('auth is derived from verified tool context, never model input',()=>{assert.throws(()=>toolOwner({session:{auth:{current:null}}} as never),BusinessWorldError);assert.throws(()=>workspaceOwner(''),BusinessWorldError);});
 await t.test('record-changing Agent tool is explicitly approval-gated',async()=>{assert.equal(typeof saveTool.approval,'function');if(typeof saveTool.approval==='function')assert.equal(await saveTool.approval({} as never),'user-approval');});
});
